name: Node.js CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test on Node.js ${{ matrix.node-version }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [24.x, 22.x, 20.x, 18.x, 16.x, 12.x, 10.x, 8.x, 6.x, 4.x]

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # 6.4.0
        with:
          node-version: ${{ matrix.node-version }}
      - name: Downgrade temp for Node 4 and 6
        if: ${{ matrix.node-version == '4.x' || matrix.node-version == '6.x' }}
        run: npm install temp@~0.8.3 --no-save
      - run: npm install
      - run: npm test